# Generated by Django 4.1.13 on 2024-09-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verify",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
