# Generated by Django 4.1.13 on 2024-09-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_is_verify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_mobile_number",
            field=models.CharField(max_length=225),
        ),
    ]
