# Generated by Django 4.1.13 on 2024-09-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_user_mobile_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_mobile_number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
